### ISSUE TITLE
No need to remove empty items

### ISSUE THREAD

**Issue by alexey-gorshkov** [whitej031788/c--paddle-webhook-verify#1]
Hi! Thank you for your repository. Long could not solve the problem of the validity of the signature. It turned out there is no need to remove elements whose empty values. I compared an example on PHP they do not delete empty elements.

```
// Now fill up SortedDictionary with any properties excluding p_signature
foreach (PropertyInfo prop in content.GetType().GetProperties())
{
   var myVal = content.GetType().GetProperty(prop.Name).GetValue(content);
   if (myVal != null && prop.Name != "p_signature")
   {
      padStuff.Add(prop.Name, myVal);
   }
}
```

**Comment by whitej031788** [comment]
Hey @alexey-gorshkov,

Glad it helped, and thanks for the heads up! I will tweak this, I did not fully disassemble the PHP serialize function, just tried to get a similar result string from an object for a Paddle webhook in .NET and then just signed it off! Took me far too long to get the Bouncy Castle RSA verification +  the serialization down, so once it was working I didn't want to fiddle with it!
